name: webapp
description: "A web Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

#------------------pkg--------------#
dependencies:
  flutter:
    sdk: flutter

  #------------- utility package-------#
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  #--------- icon------------#
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  crypto: ^3.0.0
  readmore: ^3.0.0
  firebase_core: ^2.24.2
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  fluttertoast: ^8.2.8
  #---------------pkg End----------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #----------local assets-------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/user/
    - assets/images/reviews/
    - assets/images/payment_method/
  #----------local fonts---------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-semiBold.ttf
          weight: 600
