// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy2Gc79VmOKbDu4BQi952v-rYWLtshGNE',
    appId: '1:728896956609:web:c24a4574e1bd449bb9cc40',
    messagingSenderId: '728896956609',
    projectId: 'webapp-5df99',
    authDomain: 'webapp-5df99.firebaseapp.com',
    storageBucket: 'webapp-5df99.appspot.com',
    measurementId: 'G-XGHZ5T7KTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo1G0sH8YPquIQ-0IGF6qgGKCj96nkVVU',
    appId: '1:728896956609:android:88e157197da14fb9b9cc40',
    messagingSenderId: '728896956609',
    projectId: 'webapp-5df99',
    storageBucket: 'webapp-5df99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD83c_-_WSqbxeLp5LlEwaEw5Myv3MFkjY',
    appId: '1:728896956609:ios:805bf3748e43eb74b9cc40',
    messagingSenderId: '728896956609',
    projectId: 'webapp-5df99',
    storageBucket: 'webapp-5df99.appspot.com',
    androidClientId: '728896956609-qrvphqr532ru3fat3t52qhv61mgie4lh.apps.googleusercontent.com',
    iosClientId: '728896956609-u5i67li0ukrsufsefuc2bv7u0a4cc3q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );

}